urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views # . -> pwd

app_name = "users"   



urlpatterns = [
    path("", views.index),
    # path("home/", views.home),
    path("signin/", views.signin),
    # path("afterlogin/", views.afterlogin),
    path("register/", views.register),#bydefault search func for that name so write as_view for the class
    path("aftersignup/", views.aftersignup.as_view()),
    path("aftersignin/", views.aftersignin.as_view()),
    path("details/", views.details),
    path("edit/<int:id>", views.edit, name = "edit"),
    path("delete/<int:id>", views.delete, name = "delete"),
    path("logout/", views.logout, name = "logout"),
]


models.py
from django.db import models

# Create your models here.
class Adduser(models.Model):
    username = models.CharField(max_length=100)
    email = models.CharField(max_length=200)
    password = models.CharField(max_length=500)
    address = models.CharField(max_length=500, default=None)

    def __str__(self):
        return f"{self.email}"

forms.py
from django import forms
from django.forms.forms import Form
from django.forms.widgets import PasswordInput
#inheriting a property  from froms module in which we having a class name "Form"

# Screen 1: Login Form
# 1.Email (Input)
# 2.Password (Input)
# 3.Login Button
# 4.SignUp Link

class Login(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

# Screen 2: Sign Up Form
# 1.Username
# 2.Email
# 3.Password
# 4.Confirm Password
# 5.Address


class Signup(forms.Form):
    username = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=200)
    password = forms.CharField(widget=forms.PasswordInput)
    Confirm_password = forms.CharField(widget=forms.PasswordInput)
    address = forms.CharField(max_length=1000)

#now we need to passs the form in view.py function then we pass that function into templates..
#print(dir(forms))
 

views.py
from django import http
from django.shortcuts import (get_object_or_404, render, HttpResponseRedirect)

from django.http import HttpResponse
from .forms import *
from .models import *
from django.views import View

# Create your views here.

def index(request):
    return render(request,"index.html")
    # Rendering a HTML page
def home(request):
    return HttpResponse("This is my users home page!!!!!!!!")
 
def signin(request):
    f = Login()
    return render(request, "signin.html", {'form':f})
    # we need to pass the form(class) contain in jinja through dict("keys":values) 

# def afterlogin(request):
#     form = Login(request.POST)
#     if form.is_valid(): #validating form data 
#         email = form.cleaned_data["email"]
#         password = form.cleaned_data["password"]
#         return HttpResponse(f"{email} {password}")

#     else:
#         error = "Invalid Response form"
#         form = Login()
#         return render(request, "signin.html", {'error':error})

def register(request):
    form = Signup()
    return render(request, "signup.html", {"form":form})

class aftersignup(View):
    def get(self, request):
        form = Signup()
        return render(request, "signup.html", {'form':form})

    def post(self, request):   #for post mtd req
        form = Signup(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            address = form.cleaned_data["address"] 
            try:
                Adduser.objects.get(email=email)
            except:
                Adduser.objects.create(username=username, email=email, password=password, address=address)
                form = Login()
                return render(request, "signin.html", {'form':form})
            else:
                error = "Email Already Exists"
                form = Signup()
                return render(request, "Signup.html", {'form':form, 'error':error})


        else:
            error = "invalid form"
            form = Signup()
            return render(request, "Signup.html", {'form':form, 'error':error})

class aftersignin(View):
    def get(self, request):
        if request.session.get("email"):
            return render(request, "afterlogin.html")

        else:
            error = "No such methods are allowed"
            form = Login()
            return render(request, "signin.html", {'form':form, 'error':error})
            
    def post(self, request):
        form = Login(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            try:
                obj = Adduser.objects.get(email=email)
            except:
                error = "No such user"
                form = Login()
                return render(request, "signin.html", {'form':form, 'error':error})

            else:
                if obj.password == password:
                    request.session['email'] = email
                    request.session['islogin'] = 'true'
                    request.session.set_expiry(300)
                    return render(request, "afterlogin.html")
                    #return HttpResponse("Welcome.............")
                else:
                    error = "Incorrect Passsword"
                    form = Login()
                    return render(request, "signin.html", {'form': form, 'error':error})


def details(request):
    obj1 = Adduser.objects.all()
    return render(request, "details.html", {'data' : obj1})


def delete(request, id):

 
    obj2 = get_object_or_404(Adduser, id = id)
    print(obj2)
    if request.method =="GET":
        obj2.delete()
        test = f"Users email: {obj2} deleted"
        return render(request, 'delete.html', {'test':test})
    
    return render(request, "index.html")

def edit(request, id):
    obj3 = get_object_or_404(Adduser, id = id)
    if request.method == "GET":
        form = Signup(request.POST)
 
        if form.is_valid():
            form.save()
            return render(request, 'edit.html', {'form':form})
    
        # add form dictionary to context
        
        error = "Something Wrong"
        return render(request, 'index.html', {'error':error})


def logout(request):
    del request.session['email']
    del request.session['islogin']
    form = Login()
    return render(request, "signin.html", {'form': form})






templates/afterlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Afterlogin</title>
</head>
<body>
    <li><a href="/logout"><button type="submit" value="Logout"></button></a></li>
</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    <style>
        a{
            color:white;
            font-family: 'Times New Roman', Times, serif;
            font-size:x-large;
        }

        li{
            display: inline-block;
            padding: 100px;
            
        }

        div{
            background-color: black;
            margin-top: 2%;
        }

        li:hover{
            transform: scale(1.5);
            color: tomato;
        }
    </style>    

</head>
<body style="background-color: gray;">
    <div>
        <ul>
            <li><a href="/">HOME</a></li>
            <li><a href="/signin/">SIGNIN</a></li>
            <li><a href="/details">Details</a></li>
        </ul>
    </div>

    {{test}}

</body>
</html>

templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    <style>
        a{
            color:white;
            font-family: 'Times New Roman', Times, serif;
            font-size:x-large;
        }

        li{
            display: inline-block;
            padding: 100px;
            
        }

        div{
            background-color: black;
            margin-top: 2%;
        }

        li:hover{
            transform: scale(1.5);
            color: tomato;
        }
    </style>    

</head>
<body style="background-color: gray;">
    <div>
        <ul>
            <li><a href="/">HOME</a></li>
            <li><a href="/signin/">SIGNIN</a></li>
            <li><a href="/details">Details</a></li>
        </ul>
    </div>

    {% for d in data %}
    <hr>
    <h3>UID : {{d.pk}}</h3>
    <h3>Name : {{d.username}}</h3>
    <h3>Email : {{d.email}}</h3>
    <h3>Address : {{d.address}}</h3>
    
    <a href="{% url 'users:edit' id=d.pk %}"><button type="submit">Edit</button></a>
    <a href="{% url 'users:delete' id=d.pk %}"><button type="submit">Delete</button></a>

    {% endfor %}

</body>
</html>
<!-- 
1.All User Detail except password will be shown in table
2.There will be edit and delete option in every row.
3.On Edit option a modal will be option where user details will be edited
4.On delete user details will be deleted
5.Logout option
Note:- User authentication will be through JWT token and Session Should
expire in 5 min.
Please feel free to connect in case of any query. -->


templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    <style>
        a{
            color:white;
            font-family: 'Times New Roman', Times, serif;
            font-size:x-large;
        }

        li{
            display: inline-block;
            padding: 100px;
            
        }

        div{
            background-color: black;
            margin-top: 2%;
        }

        li:hover{
            transform: scale(1.5);
            color: tomato;
        }
    </style>    

</head>
<body style="background-color: gray;">
    <div>
        <ul>
            <li><a href="/">HOME</a></li>
            <li><a href="/signin/">SIGNIN</a></li>
            <li><a href="/details">Details</a></li>
        </ul>
    </div>

    <div class="main">
        <form method="POST">
            {% csrf_token %}
     
            {{ form.as_p }}
     
            <input type="submit" value="Update">
        </form>
     
    </div>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    <style>
        a{
            color:white;
            font-family: 'Times New Roman', Times, serif;
            font-size:x-large;
        }

        li{
            display: inline-block;
            padding: 100px;
            
        }

        div{
            background-color: black;
            margin-top: 2%;
        }

        li:hover{
            transform: scale(1.5);
            color: tomato;
        }
    </style>    

</head>
<body style="background-color: gray;">
    <div>
        <ul>
            <li><a href="/">HOME</a></li>
            <li><a href="/signin/">SIGNIN</a></li>
            <li><a href="/details">Details</a></li>
        </ul>
    </div>
</body>
</html>

templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width= , initial-scale=1.0">
    <title>Document</title>

    <style>
        p{
            color: honeydew;
            font-size: 20px;
            font-style: italic;
            font-family: 'Times New Roman', Times, serif;
            text-decoration: none;
            /* text-align:center; */

        }

        a{
            color:white;
            font-family: 'Times New Roman', Times, serif;
            font-size:x-large;
        }

        li{
            display: inline-block;
            padding: 100px;
            
        }

        div{
            background-color: black;
            margin-top: 2%;
        }

        li:hover{
            transform: scale(1.5);
            color: tomato;
        }
        
    </style>

</head>
<body style="background-color: gray;">

    <div>
        <ul>
            <li><a href="/">HOME</a></li>
            <li><a href="/signin/">SIGNIN</a></li>
            <li><a href="/details">Details</a></li>
        </ul>
    </div>

    <form style="margin-top: 10%; margin-left:35%;" method="POST" action="/aftersignin/">
        <!-- csrf_token : cross site verification token -->
        {% csrf_token %} 
        {{form.as_p}}
        <input style="text-align: center;" type="submit" value="LOGIN"><br>
        
        <p style="text-decoration: none;">If you haven't register yet then just <a href="/register/">Register</a> instead.</p>
        
        
    </form>
     


</body>
</html>
<!-- 
accept for in 3 ways on html page:
form.as_p
form.as_table
form.as_ul -->  

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width= , initial-scale=1.0">
    <title>Document</title>

    <style>
        p{
            color: honeydew;
            font-size: 20px;
            font-style: italic;
            font-family: 'Times New Roman', Times, serif;

        }

        a{
            color:white;
            font-family: 'Times New Roman', Times, serif;
            font-size:x-large;
        }

        li{
            display: inline-block;
            padding: 100px;
            
        }

        div{
            background-color: black;
            margin-top: 2%;
        }

        li:hover{
            transform: scale(1.5);
            color: tomato;
        }
        
    </style>

</head>
<body style="background-color: gray;">

    <div>
        <ul>
            <li><a href="/">HOME</a></li>
            <li><a href="/signin/">SIGNIN</a></li>
            <li><a href="/details">Details</a></li>
        </ul>
    </div>
    
    <h1>{{error}}</h1>
    <form style="margin-top: 10%; margin-left:40%;" method="POST" action="/aftersignup/">
        <!-- csrf_token : cross site verification token -->
        {% csrf_token %} 
        {{form.as_p}} 
        <input style="text-align: center;" type="submit" value="Register"><br>
        <p style="text-decoration: none;">If you already register then just <a href="/signin/">LOGIN</a> instead.</p>

    </form>

</body>
</html>
<!-- 
accept for in 3 ways on html page:
form.as_p
form.as_table
form.as_ul -->  